# Generated by Django 2.0.2 on 2018-04-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvf', models.CharField(max_length=100)),
                ('cmf', models.CharField(max_length=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substances.Substance')),
            ],
        ),
    ]
