# Generated by Django 2.0.2 on 2018-04-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acda',
            options={'verbose_name': 'Компонент усредненного состава сухого воздуха', 'verbose_name_plural': 'Компоненты усредненного состава сухого воздуха'},
        ),
    ]
