# Generated by Django 2.0.2 on 2018-04-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_properties', '0003_auto_20180429_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acda',
            old_name='component',
            new_name='substance',
        ),
        migrations.RenameField(
            model_name='bpcg',
            old_name='component',
            new_name='substance',
        ),
        migrations.RenameField(
            model_name='mcc_pt',
            old_name='component',
            new_name='substance',
        ),
    ]
