# Generated by Django 2.0.2 on 2018-04-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_properties', '0004_auto_20180429_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpcg',
            old_name='substance',
            new_name='component',
        ),
    ]
