# Generated by Django 2.0.2 on 2018-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=30)),
                ('chemical_formula', models.CharField(blank=True, max_length=30)),
                ('cvf', models.CharField(max_length=100)),
                ('cmf', models.CharField(max_length=100)),
            ],
        ),
    ]
