# Generated by Django 2.0.2 on 2018-04-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_substance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACDA',
        ),
        migrations.DeleteModel(
            name='Substance',
        ),
    ]
