# Generated by Django 2.0.2 on 2018-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('chemical_formula', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Вещества',
                'verbose_name': 'Вещество',
            },
        ),
    ]
