# Generated by Django 2.0.2 on 2018-05-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(blank=True, null=True)),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substances.Substance')),
            ],
            options={
                'verbose_name': 'Информация о веществе',
                'verbose_name_plural': 'Информация о веществах',
            },
        ),
    ]
